import xlsxwriter

workbook = xlsxwriter.Workbook('macro_enabled.xlsm')
# Attach an existing VBA project (compiled as vbaProject.bin)
workbook.add_vba_project('vbaProject.bin')

ws = workbook.add_worksheet('demo')
# Write some text
ws.write("A1", "This is generated by Python!")

# Maybe guide user to run the macro
ws.write("A3", "Run the macro 'HelloWorld' from Developer > Macros.")

workbook.close()